const generateImagePath = (name) => `/images/${name}.png`;
const imageNames = [
  "analytics",
  "avatar",
  "book",
  "calender",
  "calenderwhite",
  "camraicon",
  "chain",
  "comment",
  "contentcalendercard",
  "deleteicon",
  "discord",
  "dropdown",
  "editicon",
  "facebook",
  "insta",
  "like",
  "menu",
  "menudark",
  "pinterest",
  "profileavatar",
  "share",
  "support",
  "tiktok",
  "twitch",
  "twitter",
  "uploadfile",
  "uploadicon",
  "userswitch",
  "linewhite",
  "searchicon",
  "cross",
  "crosswhite",
  "plus",
  "lineactive",
  "line",
  "menuactiv",
  "menudark",
  "calenderactive",
  "calender",
  "analyticsactive",
  "analyticsdark",
  "userswitchactive",
  "userswitchdark",
  "bookactive",
  "bookdark",
  "uploadfileactive",
  "uploadfiledark",
  "chainactive",
  "chaindark",
  "supportdark",
  "supportactive",
  "bgsvg",
  "menudarkactive",
  "calenderdarkactive",
  "analyticsdarkactive",
  "userswitchdarkactive",
  "bookdarkactive",
  "uploadfiledarkactive",
  "chaindarkactive",
  "supportdarkactive",
  "uploadicondark",
  "hideicon",
  "showicon",
  "plusgray",
  "linkedin",
  "threads",
  "reddit",
  "mastodon"
];

const IMAGES = imageNames.reduce((acc, name) => {
  acc[name.toUpperCase()] = generateImagePath(name);
  return acc;
}, {});

export { IMAGES };